# IAM审计服务配置
# Nacos连接信息必须在本地配置，不能从Nacos加载
server:
  port: 8083

spring:
  application:
    name: iam-audit-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # 从Nacos配置中心导入配置  
  config:
    import:
      - optional:nacos:iam-common.yml?refresh=true
      - optional:nacos:iam-audit-service-${spring.profiles.active}.yml?refresh=true
  
  cloud:
    nacos:
      # 服务注册发现配置
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: IAM_GROUP
        cluster-name: ${spring.profiles.active}
        metadata:
          version: ${project.version:1.0.0}
          zone: ${app.zone:default}
      
      # 配置中心连接信息
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: IAM_GROUP
        file-extension: yml
        refresh-enabled: true

# 本地日志配置（不依赖Nacos）
logging:
  file:
    name: logs/${spring.application.name}-${spring.profiles.active}.log
