server:
  port: 8081

spring:
  application:
    name: iam-auth-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr:localhost:8848}
        namespace: ${nacos.namespace:dev}
        group: IAM_GROUP
        cluster-name: ${spring.profiles.active}
        metadata:
          version: ${project.version:1.0.0}
          zone: ${app.zone:default}
      config:
        server-addr: ${nacos.server-addr:localhost:8848}
        namespace: ${nacos.namespace:dev}
        group: IAM_GROUP
        file-extension: yml
        shared-configs:
          - data-id: iam-common.yml
            group: IAM_GROUP
            refresh: true
        refresh-enabled: true
    sentinel:
      transport:
        dashboard: ${sentinel.dashboard:localhost:8080}
        port: 8718
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: ${nacos.server-addr:localhost:8848}
            namespace: ${nacos.namespace:dev}
            dataId: iam-auth-service-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
# OAuth2配置将通过Nacos统一配置管理


# 日志配置
logging:
  level:
    '[com.xiaoxin.iam]': debug
    '[org.springframework.security]': debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
