server:
  port: 8081

spring:
  application:
    name: iam-auth-service
  profiles:
    active: dev
  # OAuth2 client configuration moved to Nacos config center
  # See: config-init/config/dev/iam-auth-service-dev.yml for OAuth2 settings

# Management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

# Logging configuration is now managed by logback-spring.xml
