spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:iam_system}
    password: ${DB_PASSWORD:vB#3nK$M9qL5w@C}

  data:
    redis:
      database: 5

oauth2:
  client:
    enabled: ${OAUTH2_CLIENT_ENABLED:true}
    client-id: ${OAUTH2_CLIENT_ID:iam-system-service}
    client-secret: ${OAUTH2_CLIENT_SECRET:iam-system-secret-2024}
    token-uri: ${OAUTH2_TOKEN_URI:http://iam-auth-service/oauth2/token}
    scope: ${OAUTH2_CLIENT_SCOPE:internal:read internal:write system:read system:write}
    connect-timeout: ${OAUTH2_CONNECT_TIMEOUT:5000}
    read-timeout: ${OAUTH2_READ_TIMEOUT:10000}
    token-cache-expire: ${OAUTH2_TOKEN_CACHE_EXPIRE:3300}
    max-retries: ${OAUTH2_MAX_RETRIES:3}

mybatis-plus:
  type-aliases-package: com.xiaoxin.iam.system.entity

logging:
  level:
    "[com.xiaoxin.iam.system]": ${SYSTEM_LOG_LEVEL:info}
    "[org.springframework.security]": ${SECURITY_LOG_LEVEL:info}