spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_audit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:iam_audit}
    password: ${DB_PASSWORD:lQ@8wE$R4tY6u!H}

  data:
    redis:
      database: 4

  rocketmq:
    consumer:
      group: audit-consumer-group
      namespace: ${ROCKETMQ_NAMESPACE:dev}
      name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
      access-key: ${ROCKETMQ_ACCESS_KEY:}
      secret-key: ${ROCKETMQ_SECRET_KEY:}
      consume-mode: CONCURRENTLY
      consume-from-where: CONSUME_FROM_LAST_OFFSET
      max-reconsume-times: 16
      consume-timeout: 15

oauth2:
  client:
    enabled: ${OAUTH2_CLIENT_ENABLED:true}
    client-id: ${OAUTH2_CLIENT_ID:iam-audit-service}
    client-secret: ${OAUTH2_CLIENT_SECRET:iam-audit-secret-2024}
    token-uri: ${OAUTH2_TOKEN_URI:http://iam-auth-service/oauth2/token}
    scope: ${OAUTH2_CLIENT_SCOPE:internal.read,internal.write,audit.read,audit.write}
    connect-timeout: ${OAUTH2_CONNECT_TIMEOUT:5000}
    read-timeout: ${OAUTH2_READ_TIMEOUT:10000}
    token-cache-expire: ${OAUTH2_TOKEN_CACHE_EXPIRE:3300}
    max-retries: ${OAUTH2_MAX_RETRIES:3}

mybatis-plus:
  type-aliases-package: com.xiaoxin.iam.audit.entity

logging:
  level:
    "[com.xiaoxin.iam.audit]": ${AUDIT_LOG_LEVEL:info}
    "[org.springframework.security]": ${SECURITY_LOG_LEVEL:info}
    "[org.apache.rocketmq]": ${ROCKETMQ_LOG_LEVEL:warn}