# IAM认证服务配置文件

spring:
  cloud:
    sentinel:
      transport:
        port: 8718
        dashboard: ${SENTINEL_DASHBOARD:localhost:8181}
      datasource:
        flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            namespace: ${NACOS_NAMESPACE:dev}
            dataId: iam-auth-service-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: ${db.driver-class-name}
      url: ${db.url}
      username: ${db.username}
      password: ${db.password}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          enabled: true
          config:
            multi-statement-allow: true

  # Redis配置（认证服务专用数据库）
  data:
    redis:
      database: ${redis.database.auth}

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.xiaoxin.iam.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 认证服务特定日志配置
logging:
  level:
    com.xiaoxin.iam.auth: debug
    org.springframework.security: debug

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  username: iam_auth
  password: yP!6sN$V4gH2q@D

redis:
  database:
    auth: 2
    session: 3

oauth2:
  authorization-server:
    issuer: http://localhost:8081
    client:
      iam-web-client:
        registration:
          client-id: iam-web-client
          client-secret: "{noop}iam-web-secret"
          client-authentication-methods:
            - client_secret_basic
            - client_secret_post
          authorization-grant-types:
            - authorization_code
            - refresh_token
            - client_credentials
          redirect-uris:
            - http://localhost:8088/login/oauth2/code/iam
            - http://localhost:8088/authorized
          scopes:
            - read
            - write
            - openid
            - profile
        require-authorization-consent: true

third-party:
  wechat:
    app-id: ${WECHAT_APP_ID:}
    app-secret: ${WECHAT_APP_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/wechat
  dingtalk:
    app-id: ${DINGTALK_APP_ID:}
    app-secret: ${DINGTALK_APP_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/dingtalk
  github:
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/github

captcha:
  enabled: true
  type: math
  expire: 300
  
sms:
  provider: aliyun
  aliyun:
    access-key: ${SMS_ACCESS_KEY:}
    access-secret: ${SMS_ACCESS_SECRET:}
    sign-name: 小信云
    template-code: SMS_123456789

mail:
  host: smtp.163.com
  port: 465
  username: ${MAIL_USERNAME:}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:noreply@xiaoxin.com}
  ssl: true
