spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    password: ${redis.password:123456}
    timeout: ${redis.timeout:10000ms}
    lettuce:
      pool:
        max-active: ${redis.pool.max-active:8}
        max-wait: ${redis.pool.max-wait:-1ms}
        max-idle: ${redis.pool.max-idle:8}
        min-idle: ${redis.pool.min-idle:0}

  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          output:
            producer:
              group: iam-platform-producer-group
          input:
            consumer:
              group: iam-platform-consumer-group

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

seata:
  enabled: true
  application-id: iam-platform
  tx-service-group: iam-platform-group
  service:
    vgroup-mapping:
      iam-platform-group: default
    grouplist:
      default: localhost:8091
    enable-degrade: false
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: dev
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: dev
      group: SEATA_GROUP
