spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
      database: 1
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:8088"
              - "http://127.0.0.1:8088"
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - "Content-Type"
              - "Authorization"
              - "X-Requested-With"
            allow-credentials: true
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      routes:
        - id: iam-auth-service
          uri: lb://iam-auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
        
        - id: iam-core-service
          uri: lb://iam-core-service
          predicates:
            - Path=/api/v1/core/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
        
        - id: iam-system-service
          uri: lb://iam-system-service
          predicates:
            - Path=/api/v1/system/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 30
                redis-rate-limiter.burstCapacity: 60
        
        - id: iam-audit-service
          uri: lb://iam-audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
    
    sentinel:
      datasource:
        gw-flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            namespace: dev
            dataId: iam-gateway-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
        gw-api-group:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            namespace: dev
            dataId: iam-gateway-api-group-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
        gw-degrade:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            namespace: dev
            dataId: iam-gateway-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-degrade
        system:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            namespace: dev
            dataId: iam-gateway-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system

security:
  jwt:
    secret: xiaoxin-iam-platform-jwt-secret-key-2024
    expiration: 7200000
    refresh-expiration: 604800000

auth:
  whitelist:
    - /api/v1/auth/login
    - /api/v1/auth/logout
    - /api/v1/auth/register
    - /api/v1/auth/captcha
    - /api/v1/auth/callback/**
    - /actuator/**
    - /druid/**

rate-limit:
  enabled: true
  default-replenish-rate: 10
  default-burst-capacity: 20
  
circuit-breaker:
  enabled: true
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 2000
  minimum-number-of-calls: 10
  sliding-window-size: 100

retry:
  enabled: true
  max-attempts: 3
  backoff:
    initial-interval: 1000
    max-interval: 10000
    multiplier: 2.0

app:
  name: xiaoxin-iam-gateway
  version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,gateway"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.xiaoxin.iam.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/iam-gateway.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"