spring:
  cloud:
    nacos:
      config:
        shared-configs:
          - data-id: iam-platform-dev.yml
            group: IAM_GROUP
            refresh: true
          - data-id: iam-infrastructure-dev.yml
            group: IAM_GROUP
            refresh: true

db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_audit?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  username: iam_audit
  password: kT9!Wz2@Q

redis:
  database:
    audit: 3

mongodb:
  host: localhost
  port: 27017
  database: iam_audit
  username: 
  password: 

elasticsearch:
  enabled: true
  host: localhost
  port: 9200
  username: 
  password: 
  index-prefix: iam-audit
  
audit:
  operation-log:
    enabled: true
    storage: mysql
    retention-days: 90
    async: true
    batch-size: 100
    flush-interval-seconds: 30
  login-log:
    enabled: true
    storage: mysql
    retention-days: 180
    record-success: true
    record-failure: true
    async: true
  data-change-log:
    enabled: true
    storage: mongodb
    retention-days: 365
    tables:
      - sys_user
      - sys_role
      - sys_permission
      - sys_dept
    async: true
  exception-log:
    enabled: true
    storage: elasticsearch
    retention-days: 30
    include-stack-trace: true
    async: true

log-analysis:
  enabled: true
  anomaly-detection:
    enabled: true
    check-interval-minutes: 30
    threshold:
      login-failure-rate: 0.1
      operation-error-rate: 0.05
  statistics:
    enabled: true
    generate-interval-hours: 24
    retention-days: 365

data-cleanup:
  enabled: true
  schedule: "0 0 2 * * ?"
  batch-size: 1000
  
rocketmq:
  name-server: localhost:9876
  consumer:
    group: audit-consumer-group
    consume-thread-min: 5
    consume-thread-max: 20
    consume-message-batch-max-size: 10
