spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${DB_USERNAME:iam_auth}
    password: ${DB_PASSWORD:yP!6sN$V4gH2q@D}

  data:
    redis:
      database: 3

# OAuth2 Configuration
oauth2:
  # Authorization Server Configuration (for issuing tokens)
  authorization-server:
    issuer: ${OAUTH2_ISSUER:http://localhost:8080}
    client:
      # Frontend client configuration (corresponding to iam-client in database)
      iam-client:
        registration:
          client-id: ${OAUTH2_WEB_CLIENT_ID:iam-client}
          client-secret: ${OAUTH2_WEB_CLIENT_SECRET:"{noop}iam-secret"}
          client-authentication-methods:
            - client_secret_basic
            - client_secret_post
          authorization-grant-types:
            - authorization_code
            - refresh_token
            - client_credentials
          redirect-uris:
            - ${OAUTH2_REDIRECT_URI_1:http://localhost:3000/callback}
            - ${OAUTH2_REDIRECT_URI_2:http://localhost:3000/authorized}
            - ${OAUTH2_REDIRECT_URI_3:http://localhost:8082/callback}
            - ${OAUTH2_REDIRECT_URI_4:http://localhost:8082/authorized}
            - ${OAUTH2_REDIRECT_URI_5:http://localhost:8088/callback}
            - ${OAUTH2_REDIRECT_URI_6:http://localhost:8088/authorized}
          scopes:
            - read
            - write
        require-authorization-consent: true

  # Custom OAuth2 client configuration for Feign interceptor
  client:
    enabled: ${OAUTH2_CLIENT_ENABLED:true}
    client-id: ${OAUTH2_SERVICE_CLIENT_ID:iam-auth-service}
    client-secret: ${OAUTH2_SERVICE_CLIENT_SECRET:auth-service-secret}
    token-uri: ${OAUTH2_TOKEN_URI:http://iam-auth-service/oauth2/token}
    scope: ${OAUTH2_SERVICE_SCOPE:internal.read,internal.write,user.read,user.write}
    connect-timeout: ${OAUTH2_CONNECT_TIMEOUT:5000}
    read-timeout: ${OAUTH2_READ_TIMEOUT:10000}
    token-cache-expire: ${OAUTH2_TOKEN_CACHE_EXPIRE:3300}
    max-retries: ${OAUTH2_MAX_RETRIES:3}

mybatis-plus:
  type-aliases-package: com.xiaoxin.iam.auth.entity

logging:
  level:
    com.xiaoxin.iam.auth: DEBUG
    com.xiaoxin.iam.starter.security.oauth2: DEBUG
    feign: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http: DEBUG