db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_core?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  username: iam_core
  password: 7YDCq@TfC_L9vgP

redis:
  database:
    core: 2

business:
  user:
    default-password: 123456
    password-expire-days: 90
    max-login-attempts: 5
    lock-time-minutes: 30
  role:
    super-admin: SUPER_ADMIN
    admin: ADMIN
    user: USER
  permission:
    cache-expire-seconds: 3600
    refresh-interval-seconds: 1800

data-scope:
  enabled: true
  default-scope: DEPT_AND_CHILD
  scopes:
    ALL: 1
    CUSTOM: 2
    DEPT_AND_CHILD: 3
    DEPT_ONLY: 4
    SELF_ONLY: 5

file:
  upload:
    path: /data/uploads/
    max-size: 10MB
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - pdf
      - doc
      - docx
      - xls
      - xlsx

export:
  max-rows: 10000
  temp-path: /data/temp/
  
import:
  max-rows: 5000
  temp-path: /data/temp/
