# 数据库监控配置

# Druid监控配置
druid:
  # 监控统计配置
  stat-view-servlet:
    enabled: true
    url-pattern: /druid/*
    reset-enable: false
    login-username: admin
    login-password: druid@2024
    allow: 127.0.0.1,192.168.0.0/16
    deny: 
  
  # Web应用监控
  web-stat-filter:
    enabled: true
    url-pattern: /*
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    
  # Spring监控
  aop-patterns: com.xiaoxin.iam.*.service.*
  
  # 监控过滤器
  filters: stat,wall,log4j2
  
  # 统计配置
  filter:
    stat:
      enabled: true
      log-slow-sql: true
      slow-sql-millis: 2000
      merge-sql: true
    wall:
      enabled: true
      config:
        multi-statement-allow: true
        none-base-statement-allow: true
        comment-allow: true
        
# 数据库连接池性能配置
datasource:
  performance:
    # 连接池核心参数
    initial-size: 5           # 初始连接数
    min-idle: 5              # 最小空闲连接数
    max-active: 50           # 最大活跃连接数
    max-wait: 60000          # 获取连接等待超时时间(ms)
    
    # 连接验证配置
    validation-query: SELECT 1
    test-while-idle: true    # 空闲时验证连接
    test-on-borrow: false    # 获取连接时验证
    test-on-return: false    # 归还连接时验证
    
    # 连接回收配置
    time-between-eviction-runs-millis: 60000    # 检测间隔时间(ms)
    min-evictable-idle-time-millis: 300000      # 连接最小空闲时间(ms)
    max-evictable-idle-time-millis: 900000      # 连接最大空闲时间(ms)
    
    # 预处理语句配置
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    
    # 连接泄漏检测
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    log-abandoned: true
    
    # 异常重连配置
    connection-error-retry-attempts: 3
    break-after-acquire-failure: true
    
# 数据库性能监控指标
monitoring:
  metrics:
    # 连接池指标
    connection-pool:
      - active-count          # 活跃连接数
      - idle-count           # 空闲连接数
      - wait-count           # 等待连接数
      - connect-count        # 累计连接次数
      - close-count          # 累计关闭次数
      
    # SQL执行指标  
    sql-execution:
      - execute-count        # 执行次数
      - execute-time         # 执行时间
      - slow-sql-count       # 慢SQL次数
      - error-count          # 错误次数
      
    # 事务指标
    transaction:
      - commit-count         # 提交次数
      - rollback-count       # 回滚次数
      - transaction-time     # 事务时间
      
  # 告警配置
  alerts:
    # 连接池告警
    connection-pool:
      active-rate-threshold: 0.8    # 活跃连接比例告警阈值
      wait-count-threshold: 10      # 等待连接数告警阈值
      
    # SQL性能告警  
    sql-performance:
      slow-sql-threshold: 2000      # 慢SQL阈值(ms)
      error-rate-threshold: 0.01    # SQL错误率告警阈值
      
    # 事务告警
    transaction:
      rollback-rate-threshold: 0.05 # 事务回滚率告警阈值
      long-transaction-threshold: 30000 # 长事务告警阈值(ms)

# 数据库优化建议
optimization:
  # 连接池优化
  connection-pool:
    - name: "合理设置连接池大小"
      description: "根据应用并发量调整initial-size、min-idle、max-active参数"
      recommendation: "一般情况下 max-active = CPU核数 * 2"
      
    - name: "启用连接验证"
      description: "开启test-while-idle避免连接失效"
      recommendation: "设置合理的validation-query和检测间隔"
      
    - name: "配置连接回收"
      description: "及时回收空闲连接释放资源"
      recommendation: "设置min-evictable-idle-time-millis为5分钟"
      
  # SQL优化
  sql-optimization:
    - name: "监控慢SQL"
      description: "识别和优化执行时间超过阈值的SQL"
      recommendation: "设置slow-sql-millis为2000ms，定期分析慢SQL"
      
    - name: "使用预处理语句"
      description: "启用pool-prepared-statements提高性能"
      recommendation: "合理设置max-pool-prepared-statement-per-connection-size"
      
  # 事务优化
  transaction-optimization:
    - name: "控制事务范围"
      description: "避免长事务影响系统性能"
      recommendation: "将非数据库操作移出事务范围"
      
    - name: "合理设置隔离级别"
      description: "根据业务需求选择合适的事务隔离级别"
      recommendation: "一般使用READ_COMMITTED级别"
