# IAM认证服务开发环境配置

# 数据库配置
db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://rm-bp1refbfnvk2t7235do.mysql.rds.aliyuncs.com:3306/iam_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  username: iam_auth
  password: yP!6sN$V4gH2q@D

# Redis配置
redis:
  host: localhost
  port: 6379
  password: eW7$zR2p#9qL!5v@1sKx8nP6dYf*4gHj
  database:
    auth: 1

# OAuth2 配置
spring:
  security:
    oauth2:
      authorization-server:
        issuer: http://localhost:8081
        client:
          iam-web-client:
            registration:
              client-id: iam-web-client
              client-secret: "{noop}iam-web-secret"
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - http://localhost:8088/login/oauth2/code/iam
                - http://localhost:8088/authorized
              scopes:
                - read
                - write
                - openid
                - profile
            require-authorization-consent: true

# JWT配置
jwt:
  secret: xiaoxin-iam-jwt-secret-key-2024
  expiration: 3600000
  refresh-expiration: 604800000

# 第三方登录配置
third-party:
  wechat:
    app-id: ${WECHAT_APP_ID:}
    app-secret: ${WECHAT_APP_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/wechat
  dingtalk:
    app-id: ${DINGTALK_APP_ID:}
    app-secret: ${DINGTALK_APP_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/dingtalk
  github:
    client-id: ${GITHUB_CLIENT_ID:}
    client-secret: ${GITHUB_CLIENT_SECRET:}
    redirect-uri: http://localhost:8081/auth/callback/github

# 验证码配置
captcha:
  enabled: true
  type: math
  expire: 300
  
# 短信配置
sms:
  provider: aliyun
  aliyun:
    access-key: ${SMS_ACCESS_KEY:}
    access-secret: ${SMS_ACCESS_SECRET:}
    sign-name: 小信云
    template-code: SMS_123456789

# 邮件配置
mail:
  host: smtp.163.com
  port: 465
  username: ${MAIL_USERNAME:}
  password: ${MAIL_PASSWORD:}
  from: ${MAIL_FROM:noreply@xiaoxin.com}
  ssl: true
