# IAM网关开发环境配置

# 网关路由配置
gateway:
  routes:
    # 认证服务路由
    auth-service:
      predicates:
        - Path=/api/v1/auth/**
      filters:
        - StripPrefix=3
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20
            redis-rate-limiter.burstCapacity: 40
            redis-rate-limiter.requestedTokens: 1
    
    # 核心服务路由
    core-service:
      predicates:
        - Path=/api/v1/core/**
      filters:
        - StripPrefix=3
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
    
    # 系统服务路由
    system-service:
      predicates:
        - Path=/api/v1/system/**
      filters:
        - StripPrefix=3
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 30
            redis-rate-limiter.burstCapacity: 60
    
    # 审计服务路由
    audit-service:
      predicates:
        - Path=/api/v1/audit/**
      filters:
        - StripPrefix=3
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20

# Redis配置（用于限流）
redis:
  host: localhost
  port: 6379
  password: eW7$zR2p#9qL!5v@1sKx8nP6dYf*4gHj
  database:
    gateway: 0

# 认证配置
auth:
  # 白名单路径（不需要认证）
  whitelist:
    - /api/v1/auth/login
    - /api/v1/auth/logout
    - /api/v1/auth/register
    - /api/v1/auth/captcha
    - /api/v1/auth/callback/**
    - /actuator/**
    - /druid/**
  
  # JWT配置
  jwt:
    secret: xiaoxin-iam-jwt-secret-key-2024
    expiration: 3600000
    header: Authorization
    prefix: Bearer 

# 限流配置
rate-limit:
  enabled: true
  default-replenish-rate: 10
  default-burst-capacity: 20
  
# 熔断配置
circuit-breaker:
  enabled: true
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 2000
  minimum-number-of-calls: 10
  sliding-window-size: 100

# 重试配置
retry:
  enabled: true
  max-attempts: 3
  backoff:
    initial-interval: 1000
    max-interval: 10000
    multiplier: 2.0

# 跨域配置
cors:
  allowed-origins:
    - http://localhost:8088
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

# 日志配置
logging:
  level:
    com.xiaoxin.iam.gateway: debug
    org.springframework.cloud.gateway: info
    org.springframework.security: debug
