global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # IAM平台服务监控
  - job_name: 'iam-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-auth-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-user-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-permission-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-organization-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-audit-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-notification-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-config-service'
    static_configs:
      - targets: ['host.docker.internal:8087']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'iam-frontend'
    static_configs:
      - targets: ['host.docker.internal:8088']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  # MySQL监控
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nacos监控
  - job_name: 'nacos'
    static_configs:
      - targets: ['nacos:8848']

  # RocketMQ监控
  - job_name: 'rocketmq-nameserver'
    static_configs:
      - targets: ['rocketmq-nameserver:9876']

  - job_name: 'rocketmq-broker'
    static_configs:
      - targets: ['rocketmq-broker:10911']

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
