server:
  port: 8080

spring:
  application:
    name: iam-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: iam-common.yml
            group: DEFAULT_GROUP
            refresh: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证服务
        - id: iam-auth-service
          uri: lb://iam-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 用户服务
        - id: iam-user-service
          uri: lb://iam-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        # 权限服务
        - id: iam-permission-service
          uri: lb://iam-permission-service
          predicates:
            - Path=/permission/**
          filters:
            - StripPrefix=1
        # 组织服务
        - id: iam-organization-service
          uri: lb://iam-organization-service
          predicates:
            - Path=/organization/**
          filters:
            - StripPrefix=1
        # 审计服务
        - id: iam-audit-service
          uri: lb://iam-audit-service
          predicates:
            - Path=/audit/**
          filters:
            - StripPrefix=1
        # 通知服务
        - id: iam-notification-service
          uri: lb://iam-notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        # 配置服务
        - id: iam-config-service
          uri: lb://iam-config-service
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1
        # 前端服务
        - id: iam-frontend
          uri: lb://iam-frontend
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s

# Sentinel配置
spring.cloud.sentinel:
  transport:
    dashboard: localhost:8080
    port: 8719
  datasource:
    ds1:
      nacos:
        server-addr: localhost:8848
        dataId: iam-gateway-flow-rules
        groupId: SENTINEL_GROUP
        rule-type: flow

# 日志配置
logging:
  level:
    com.xiaoxin.iam: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
