server:
  port: 8080

spring:
  application:
    name: iam-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"