server:
  port: 8080

spring:
  application:
    name: iam-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr:localhost:8848}
        namespace: ${nacos.namespace:dev}
        group: IAM_GROUP
        cluster-name: ${spring.profiles.active}
        metadata:
          version: ${project.version:1.0.0}
          zone: ${app.zone:default}
      config:
        server-addr: ${nacos.server-addr:localhost:8848}
        namespace: ${nacos.namespace:dev}
        group: IAM_GROUP
        file-extension: yml
        shared-configs:
          - data-id: iam-common.yml
            group: IAM_GROUP
            refresh: true
        refresh-enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证服务
        - id: iam-auth-service
          uri: lb://iam-auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
        # 核心服务
        - id: iam-core-service
          uri: lb://iam-core-service
          predicates:
            - Path=/api/v1/core/**
          filters:
            - StripPrefix=3
        # 系统服务
        - id: iam-system-service
          uri: lb://iam-system-service
          predicates:
            - Path=/api/v1/system/**
          filters:
            - StripPrefix=3
        # 审计服务
        - id: iam-audit-service
          uri: lb://iam-audit-service
          predicates:
            - Path=/api/v1/audit/**
          filters:
            - StripPrefix=3
        # 前端服务
        - id: iam-frontend
          uri: lb://iam-frontend
          predicates:
            - Path=/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s

    sentinel:
      transport:
        dashboard: ${sentinel.dashboard:localhost:8080}
        port: 8717
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: ${nacos.server-addr:localhost:8848}
            namespace: ${nacos.namespace:dev}
            dataId: iam-gateway-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow

# 日志配置
logging:
  level:
    com.xiaoxin.iam: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
