# IAM Core Service Configuration
# Nacos connection must be configured locally, cannot be loaded from Nacos
server:
  port: 8082

spring:
  application:
    name: iam-core-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Import configuration from Nacos config center
  config:
    import:
      - optional:nacos:iam-common.yml?refresh=true
      - optional:nacos:iam-core-service-${spring.profiles.active}.yml?refresh=true
  
  cloud:
    nacos:
      # Service registration and discovery configuration
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: IAM_GROUP
        cluster-name: ${spring.profiles.active}
        metadata:
          version: ${project.version:1.0.0}
          zone: ${app.zone:default}
      
      # Config center connection
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: IAM_GROUP
        file-extension: yml
        refresh-enabled: true

# Local logging configuration (not dependent on Nacos)
logging:
  file:
    name: logs/${spring.application.name}-${spring.profiles.active}.log
