server:
  port: 8082

spring:
  application:
    name: iam-core-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.xiaoxin.iam: debug
    org.springframework.security: debug